#! /bin/sh

DATE=$(date +"%Y-%m-%d %H.%M.%S")

MODS=$(git status -s | wc -l)
if [ $MODS -ne 0 ] ; then
   MODS_SUFFIX=-x$MODS
else
   MODS_SUFFIX=
fi

COMMIT=$(git rev-parse HEAD)
CONFIG=$(md5sum config.h | awk '{ print $1 }')

VERSION=${COMMIT}${MODS_SUFFIX}

TEXT_SIZE=$(objdump -h build/eZChronos.elf | awk '/\.text/ { printf "%d", strtonum("0x" $3) }')
RODATA_SIZE=$(objdump -h build/eZChronos.elf | awk '/\.rodata/ { printf "%d", strtonum("0x" $3) }')
DATA_SIZE=$(objdump -h build/eZChronos.elf | awk '/\.data/ { printf "%d", strtonum("0x" $3) }')
BSS_SIZE=$(objdump -h build/eZChronos.elf | awk '/\.bss/ { printf "%d", strtonum("0x" $3) }')

printf "%s\t%s\t%s\t%d\t%d\t%d\t%d\n" "$DATE" $VERSION $CONFIG $TEXT_SIZE $RODATA_SIZE $DATA_SIZE $BSS_SIZE 

